myproject: main.o dicision.o comparisons.o tests.o conclusion.o
	g++ main.o dicision.o comparisons.o tests.o conclusion.o -o myproject

main.o: main.cpp
	g++ -c main.cpp 

dicision.o: dicision.cpp
	g++ -c dicision.cpp 

comparisons.o: comparisons.cpp
	g++ -c comparisons.cpp

tests.o: tests.cpp
	g++ -c tests.cpp

conclusion.o: conclusion.cpp
	g++ -c conclusion.cpp











